name: Deploy website on push
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to sldevs.web.lk
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files via SSH (Rsync)
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          # Private Key stored in GitHub Secrets
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # Remote Host (e.g., sedna.lambdasoul.x10.mx)
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          # Remote User (e.g., your ssh username)
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          # The directory on the server to deploy to (IMPORTANT: Must end with /)
          TARGET: ${{ secrets.REMOTE_TARGET }} 
          # Source directory to deploy (usually ./ or ./dist/ for built sites)
          SOURCE: "./"
          # Rsync arguments (archive, verbose, compress, delete files not in source)
          ARGS: "-avz --delete"
