name: Deploy website on push
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to sldevs.web.lk
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files via SSH (Rsync)
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SOURCE: "./"
          REMOTE_PORT: 2222
          # 👇 Change this back to just these flags
          ARGS: "-avz --delete"